import './globals.css'
import '../styles/bootstrap.css'
import '../styles/bootstrap-utilities.css'
import '../styles/bootstrap-reboot.css'
import '../styles/responsive.css'
import '../styles/style.css'
import '../styles/style_base.css'

import styles from '@/styles/style-e.module.css'
import NavBar from '@/layouts/navbar'
import Footer from '@/layouts/footer'
import Global_context_Provider from '@/context/global_context'

export const metadata = {
  title: 'I3DE',
  description: 'Generated by create next app',
  // script : "https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"
}



export default function RootLayout({ children }) {
 

  return (
    <html lang="en">
      <Global_context_Provider>
        <body>
          <NavBar/>
          <div className='vide'></div>
          {children}
          <footer className={styles.footer}></footer>
          <Footer />
        </body>
      </Global_context_Provider>
    </html>
  )
}
